name: Build All Extensions

on:
  push:
    branches: [Aniwatch]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Set environment variables for CI
        run: |
          echo "CI_CHUNK_SIZE=9999" >> $GITHUB_ENV
          echo "CI_CHUNK_NUM=0" >> $GITHUB_ENV
          echo "CI=true" >> $GITHUB_ENV

      - name: Set execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build All Extensions
        run: ./gradlew assembleDebug

      - name: Collect all APKs
        run: |
          mkdir -p output
          find src -type f -name "*.apk" -exec cp {} output/ \;

      - name: Upload to apk-builds branch
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch
          git switch -c apk-builds origin/apk-builds || git checkout --orphan apk-builds
          git rm -rf . || true
          mkdir -p all-apks
          cp output/*.apk all-apks/
          git add all-apks/
          git commit -m "Upload all extension APKs [CI]" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/NotScrape/extensions.git apk-builds --force
          
